const projectsData = [
    {
      id: 1,
      title: "Portfolio Website",
      description: "webite about yourself",
      image: "/images/projects/1.jpg",
      tag: ["All", "Web"],
      gitUrl: "/",
      previewUrl: "https://nails-decoration.vercel.app/",
    },
    {
      id: 2,
      title: "Carleybay",
      description: "childs care project",
      image: "/images/projects/2.jpg",
      tag: ["All", "Web"],
      gitUrl: "/",
      previewUrl: "https://hinna-henna-main.vercel.app/",
    },
    {
      id: 3,
      title: "E-commerce Application",
      description: "Project 3 description",
      image: "/images/projects/3.jpg",
      tag: ["All", "Web"],
      gitUrl: "/",
      previewUrl: "https://salon-frontend-master.vercel.app/",
    },
    {
      id: 4,
      title: "Cooking Application",
      description: "Project 4 description",
      image: "/images/projects/4.jpg",
      tag: ["All", "Mobile"],
      gitUrl: "/",
      previewUrl: "https://shofy-beauty-and-cosmetics-ecommerce-client-main.vercel.app/",
    },
    {
      id: 5,
      title: "CoinChance",
      description: "BLockchain and wallet joining",
      image: "/images/projects/5.jpg",
      tag: ["All", "Web"],
      gitUrl: "/",
      previewUrl: "https://real-estate-main-amber.vercel.app/",
    },
    {
      id: 6,
      title: "Full-stack Roadmap",
      description: "Project 5 description",
      image: "/images/projects/6.jpg",
      tag: ["All", "Web"],
      gitUrl: "/",
      previewUrl: "https://travelwebsite-master.vercel.app/",
    },
    {
      id: 7,
      title: "Full-stack Roadmap",
      description: "Project 5 description",
      image: "/images/projects/7.jpg",
      tag: ["All", "Web"],
      gitUrl: "/",
      previewUrl: "https://travelling-to-africs.vercel.app/",
    },
    {
      id: 8,
      title: "Full-stack Roadmap",
      description: "Project 5 description",
      image: "/images/projects/8.jpg",
      tag: ["All", "Web"],
      gitUrl: "/",
      previewUrl: "https://furniture-two-rho.vercel.app/",
    },
    {
      id: 9,
      title: "Full-stack Roadmap",
      description: "Project 5 description",
      image: "/images/projects/9.jpg",
      tag: ["All", "Web"],
      gitUrl: "/",
      previewUrl: "https://travel-navy-sigma.vercel.app/",
    },
    {
      id: 10,
      title: "Full-stack Roadmap",
      description: "Project 5 description",
      image: "/images/projects/10.jpg",
      tag: ["All", "Web"],
      gitUrl: "/",
      previewUrl: "https://food-theta-seven.vercel.app/",
    },
    
  ];